version: "3.8"
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    env_file: .env
    ports:
      - "4566:4566"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  form-service:
    build: ./form-service
    ports:
      - "8080:8080"
    depends_on:
      - localstack
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
